# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.network "private_network", ip: "192.168.44.21"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = [File.expand_path('../cookbooks', __FILE__)]
    chef.add_recipe "apt"
    chef.add_recipe "openldap::server"
    chef.json = {
      "openldap" => {
        "tls_enabled" => false,
        "rootpw" => "wibble!"
      }
    }
  end
end
